WIDTH = 600 # width of the screen
HEIGHT = 600 # height of the screen
LINE_WIDTH = 15 # line width
WIN_LINE_WIDTH = 15 # win line width
BOARD_ROWS = 3 # number of rows
BOARD_COLS = 3 # number of cols
SQUARE_SIZE = 200 # size of box
CIRCLE_RADIUS = 60 # radius of circle
CIRCLE_WIDTH = 15 # width of cirlcle
CROSS_WIDTH = 25 # width of cross
SPACE = 55 # space
RED = (255, 0, 0) # red color
BG_COLOR = "lemonchiffon" # bg color
LINE_COLOR = (245, 152, 66) # line color for boxes
CIRCLE_COLOR = (155, 155, 155) # circle color for O player
CROSS_COLOR = (66, 66, 66) # cross color for X player
CHIP_FONT = 400 # chip font
GAME_OVER_FONT = 40 # game over font
CHIP_X = 'X' # x chip
CHIP_O = "O" # o chip
START_COLOR = "black"
BUTTON_FONT = 25 # font for the button
SCREEN_FONT = 65 # font for the screen
TEXT_COLOR = "white"
BUTTON_TEXT = "black"
BUTTON_HEIGHT = 50 # button height
BUTTON_WIDTH = WIDTH/6 # button width
BUTTON_COLOR = "white"
BUTTON_X = 245
BUTTON_Y = 3*HEIGHT/4